Alistair/4005 refresh sdhs logins
THIS-Institute/s3-to-sdhs pull request #16
Opened 2022-10-03 11:19 UTC by alistairclark

https://this.tpondemand.com/RestUI/Board.aspx#page=profile&boardPopup=userstory/4005/silent

I'm not sure how useful the notifications are for now. They are being recorded but some improvements might be needed to enable us to view them more easily.

2022-10-04 09:52 UTC, this-andy commented on src/main.py
> +def refresh_login_credentials(event, context):
This basically looks fine, but I'd suggest a slight refactoring so that methods do just one thing.
Suggest splitting into two methods 
- one that does the core refresh processing and returns two lists
- one that takes the two lists and creates notifications
That way we could call refresh with different reporting method in future

2022-10-04 09:55 UTC, this-andy requested changes
See individual comment.  Would be a slight improvement and easily allow us to add new calling methods in future without having to refactor.
In fact you could also extract the core of the loop and have a method for refreshing a single account.  Again might be useful in future

2022-10-06 11:16 UTC, alistairclark commented
Have refactored and added some docstrings.

2022-10-06 11:46 UTC, this-andy approved these changes

2022-10-06 12:19 UTC, merged