4559 Setup CICD
THIS-Institute/s3-to-sdhs pull request #21
Opened 2023-03-03 11:51 UTC by sophiemachin

2023-03-03 11:51 UTC, this-andy commented
https://this.tpondemand.com/entity/4559

2023-03-07 11:16 UTC, this-andy requested changes

2023-03-07 11:16 UTC, this-andy commented on requirements.txt
> +https://github.com/THIS-Institute/thiscovery-dev-tools/archive/refs/heads/sophie-CAPABILITY_NAMED_IAM.zip
Is this right?  It seems odd to have a developer-specific entry in the requirements file.

2023-03-07 11:17 UTC, sophiemachin commented on requirements.txt
> +https://github.com/THIS-Institute/thiscovery-dev-tools/archive/refs/heads/sophie-CAPABILITY_NAMED_IAM.zip
Oh good spot, I need to update dev tools to be able to handle this properly

2023-03-07 15:22 UTC, sophiemachin commented on requirements.txt
> +https://github.com/THIS-Institute/thiscovery-dev-tools/archive/refs/heads/sophie-CAPABILITY_NAMED_IAM.zip
It turns out I didn't need the custom capability after all. I've put back the requirements.txt, so this can be be reviewed.

2023-03-07 15:37 UTC, this-andy approved these changes

2023-03-07 15:40 UTC, merged